services:
  # Main API service (Restructured Backend)
  api:
    build: .
    container_name: blocking-responses-api-restructured
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      # Required - set your OpenAI API key
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Optional configuration
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gpt-4o-mini}
      - JUDGE_MODEL=${JUDGE_MODEL:-gpt-4o-mini}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DELAY_TOKENS=${DELAY_TOKENS:-20}
      - DELAY_MS=${DELAY_MS:-250}
      - RISK_THRESHOLD=${RISK_THRESHOLD:-0.9}
      - JUDGE_THRESHOLD=${JUDGE_THRESHOLD:-0.8}
      - ENABLE_JUDGE=${ENABLE_JUDGE:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:80}
    volumes:
      # Mount source for development (comment out for production)
      - ./app:/app/app
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes: {}

networks:
  default:
    name: blocking-responses-backend-network